<?php

/*

Pixelpost version 1.3
Language file: english/default

Pixelpost www: http://www.pixelpunk.se/software/
Contact: pixelpost@pixelpunk.se
Copyright (c) 2004 shapestyle graphic design + code<http://www.shapestyle.se>
License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or 
in other languages.
*/

/* Dont edit                    Edit                                                        */

// IMAGE NAVIGATION
$lang_previous              = "Previous";
$lang_next                  = "Next";
$lang_no_previous           = "No Previous Image";
$lang_no_next               = "No Next Image";
$lang_browse_select_category    = "Select Category";
$lang_browse_all            = "All";

// COMMENTS
$lang_message_missing_image = "No image selected. Comment was not saved.";
$lang_message_missing_comment   = "No message input. Comment was not saved.";
$lang_visit_homepage        = "Visit Homepage";
$lang_no_comments_yet       = "No Comments Yet.";
$lang_comment_thank_you     = "Thank you for visiting and taking the time to comment on a picture.";
$lang_comment_redirect      = "Please click to be transferred back.";
$lang_comment_page_title    = "Comment";
$lang_comment_popup         = "Comments";

// EXIF DATA
$lang_exposure              = "Exposure:";
$lang_aperture              = "Aperture:";
$lang_capture_date          = "Capture Date:";
$lang_focal                 = "Focal:";
$lang_camera_maker          = "Camera Maker:";
$lang_camera_model          = "Camera Model:";
$lang_flash_fired           = "Flash: Fired";
$lang_flash_not_fired       = "Flash: Not Fired";



?>