<?php

/*

Pixelpost version 1.3
Language file: english/default
Translation: Connie Mueller-Goedecke

Pixelpost www: http://www.pixelpunk.se/software/
Contact: pixelpost@pixelpunk.se
Copyright (c) 2004 shapestyle graphic design + code <http://www.shapestyle.se>
License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
*/

/* Dont edit                    Edit                                                        */

// IMAGE NAVIGATION
$lang_previous              = "zur&uuml;ck";
$lang_next                  = "weiter";
$lang_no_previous           = "keine weiteren Bilder";
$lang_no_next               = "keine neueren Bilder";
$lang_browse_select_category    = "Kategorie w&auml;hlen";
$lang_browse_all            = "alle";

// COMMENTS
$lang_message_missing_image = "Kein Bild ausgew&auml;hlt. Der Kommentar wurde nicht gespeichert.";
$lang_message_missing_comment   = "Kein Text eingegeben. Der Kommentar wurde nicht gespeichert.";
$lang_visit_homepage        = "Zur Startseite";
$lang_no_comments_yet       = "Noch keine Kommentare.";
$lang_comment_thank_you     = "Danke dass Sie sich Zeit f&uuml;r einen Kommentar genommen haben.";
$lang_comment_redirect      = "Klicken Sie hier um zur&uuml;ckzukehren";
$lang_comment_page_title    = "Kommentar";
$lang_comment_popup         = "Kommentare";

// EXIF DATA
$lang_exposure              = "Blende:";
$lang_aperture              = "Verschlusszeit:";
$lang_capture_date          = "Aufnahmedatuem:";
$lang_focal                 = "Fokus:";
$lang_camera_maker          = "Hersteller:";
$lang_camera_model          = "Kamera-Modell:";
$lang_flash_fired           = "Blitz:";
$lang_flash_not_fired       = "Kein Blitz";

?>