<?php

/*

Pixelpost version 1.3
Language file: swedish/svenska
Not quite final...

Pixelpost www: http://www.pixelpunk.se/software/
Contact: pixelpost@pixelpunk.se
Copyright (c) 2004 shapestyle graphic design + code<http://www.shapestyle.se>
License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or 
in other languages.
*/

/* Dont edit                    Edit                                                        */

// IMAGE NAVIGATION
$lang_previous              = "Föregående";
$lang_next                  = "Nästa";
$lang_no_previous           = "Ingen bild";
$lang_no_next               = "Ingen bild";
$lang_browse_select_category    = "Välj kategori";
$lang_browse_all            = "Alla";

// COMMENTS
$lang_message_missing_image = "Ingen bild vald, kommentaren sparades inte.";
$lang_message_missing_comment   = "Inget meddelande, kommentaren sparades inte.";
$lang_visit_homepage        = "Besök hemsida";
$lang_no_comments_yet       = "Inga kommentarer ännu.";
$lang_comment_thank_you     = "Tack för ditt besök och för att du tog dig tid att kommentera en bild!";
$lang_comment_redirect      = "Klicka för att gå tillbaka.";
$lang_comment_page_title    = "Kommentera";
$lang_comment_popup         = "Kommentarer";

// EXIF DATA
$lang_exposure              = "Exponering:";
$lang_aperture              = "Bländare:";
$lang_capture_date          = "Tagen:";
$lang_focal                 = "Brännvidd:";
$lang_camera_maker          = "Kameramärke:";
$lang_camera_model          = "Kameramodell:";
$lang_flash_fired           = "Blixt: Avfyrad";
$lang_flash_not_fired       = "Blixt: Ej avfyrad";



?>