<div id="leftmenu">


<h3>Navigation</h3>
<ul>
	<li><a href="./">Accueil</a></li>
	<li><a href="<?php echo kmSettings()?>">Site public</a>
</ul>

<h3>Images</h3>
<ul>
	<li><a href="./image.php">Nouvelle image</a></li>
	<li><a href="./images.php?op=list">Gestion des images</a></li>
	<li><a href="./images.php?op=operations">Opérations</a></li>
</ul>
<h3>Catégories</h3>
<ul>
	<li><a href="./categories.php">Gestion</a></li>
</ul>
<h3>Statistiques</h3>
<ul>
	<li><a href="./stats.php">Résumé</a></li>
	<li><a href="./stats.php?op=detail">Détails</a></li>
</ul>
<h3>Configuration</h3>
<ul>
	<li><a href="./preferences.php">Préférences personnelles</a></li>
	<li><a href="./users.php">Utilisateurs</a></li>
	<li><a href="./themes.php">Thèmes</a></li>
	<li><a href="./config.php">Paramètres</a></li>
	<li><a href="./config.php?op=info">Informations</a></li>
</ul>


<h3>&nbsp;</h3>
<ul>
	<li><a href="./?logout=yes">Déconnexion</a></li>
</ul>
</div>